name: setup-this-repository
description: Set up Python and uv, and install dependencies
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: false

    - name: Install dependencies
      run: uv sync --dev --frozen
      shell: bash
